### PR TITLE
#163225797 modify response 

### PR DESCRIPTION
**Pull request by wathigo**
### What does this PR do?
Modifies endpoints response format to match that in the requirement specification for the challenge.

### Description of the task to be completed.
Modification of endpoint response to match the one specified in the requirement specification for the challenge.

### Any background context you want to provide?
None

### How can this be manually tested?
Open the terminal.
Enter git clone https://github.com/wathigo/Questioner.git
Navigate to the cloned repository.
Enter flask run.
Test the endpoints using postman.

### Relevant PT stories
#163225797

### Screenshots
screenshot from 2019-01-15 11-14-56
screenshot from 2019-01-15 11-16-38
screenshot from 2019-01-15 11-17-12

### CODE REVIEW

**Comment by SamueGathua** [comment]
good work

**Comment by wathigo** [comment]
Thank you.

**Comment by MainaEK** [comment]
Great work

**Comment by NjuiNjeri** [comment]
Meets the requirements I'd say.

**Pull request merged**
