### PR TITLE
#163216237 Add validators tests 

### PR DESCRIPTION
**Pull request by wathigo**
### What does this PR do?
Adds tests for validators.

### Description of the task to be completed.
Implementation of tests to test the requests data validators to ensure that the validators are working as the as per the requirements. 

### How can this be manually tested?
Open the terminal.
Enter git clone https://github.com/wathigo/Questioner.git
Navigate to the cloned repository.
Enter 'coverage run --source=app -m pytest && coverage report' command.

### Any Background context you want to provide?
None

### Relevant PT stories
#163216237

### Screenshots
screenshot from 2019-01-15 02-17-46

### Questions:

### CODE REVIEW

**Comment by Ogollah** [comment]
Good job

**Comment by wathigo** [comment]
Thanks

**Comment by colMike** [comment]
Awesome job.

**Comment by wathigo** [comment]
Thanks guys

**Pull request merged**
